{% set version = "0.5.0" %}

package:
  name: model_metadata
  version: {{ version }}

source:
  url: https://github.com/csdms/model_metadata/archive/v{{ version }}.tar.gz
  sha256: d3168813642d5de5dde963c11456ae77f7843bee14daf34b76ee8088d699a784

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - mmd = model_metadata.cli.main:main
    - mmd-dump = model_metadata.cli.main_dump:main
    - mmd-find = model_metadata.cli.main_find:main
    - mmd-install = model_metadata.cli.main_install:main
    - mmd-query = model_metadata.cli.main_query:main
    - mmd-stage = model_metadata.cli.main_stage:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - packaging
    - pyyaml
    - six
    - jinja2
    - scripting
    - binaryornot

test:
  commands:
    - mmd --help
    - mmd-dump --help
    - mmd-find --help
    - mmd-install --help
    - mmd-query --help
    - mmd-stage --help

about:
  home: http://github.com/csdms/model_metadata
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for working with CSDMS Model Metadata
  description: |
    The CSDMS model_metadata Python package provides tools for working
    with CSDMS Model Metadata. Contained within this package are tools for
    (1) parsing model metadata, (2) staging model simulations, (3)
    validating model input parameters, and (4) running model simulations.
  dev_url: http://github.com/csdms/model_metadata

extra:
  recipe-maintainers:
    - mcflugen
