{% set version = "0.7.0" %}

package:
  name: model_metadata
  version: {{ version }}

source:
  url: https://github.com/csdms/model_metadata/archive/v{{ version }}.tar.gz
  sha256: 2cc40cb056124cfd39a2b35555017544fffefadf6f840cf8d09c744d20eabda2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - mmd = model_metadata.cli.main:mmd

requirements:
  build:
    - python
    - pip
  run:
    - python
    - packaging
    - pyyaml
    - jinja2
    - binaryornot
    - click

test:
  commands:
    - mmd --help
    - mmd find --help
    - mmd query --help
    - mmd stage --help

about:
  home: http://github.com/csdms/model_metadata
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for working with CSDMS Model Metadata
  description: |
    The CSDMS model_metadata Python package provides tools for working
    with CSDMS Model Metadata. Contained within this package are tools for
    (1) parsing model metadata, (2) staging model simulations, (3)
    validating model input parameters, and (4) running model simulations.
  dev_url: http://github.com/csdms/model_metadata

extra:
  recipe-maintainers:
    - mcflugen
