{% set version = "0.6.0" %}

package:
  name: model_metadata
  version: {{ version }}

source:
  url: https://github.com/csdms/model_metadata/archive/v{{ version }}.tar.gz
  sha256: bd9d5fbbd2965cf476fc5474003ac7bd9d925c75e4e71183e6cbdd13f211192f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - mmd = model_metadata.cli.main:mmd

requirements:
  build:
    - python
    - pip
  run:
    - python
    - packaging
    - pyyaml
    - six
    - jinja2
    - scripting
    - binaryornot
    - click

test:
  commands:
    - mmd --help
    - mmd find --help
    - mmd query --help
    - mmd stage --help

about:
  home: http://github.com/csdms/model_metadata
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for working with CSDMS Model Metadata
  description: |
    The CSDMS model_metadata Python package provides tools for working
    with CSDMS Model Metadata. Contained within this package are tools for
    (1) parsing model metadata, (2) staging model simulations, (3)
    validating model input parameters, and (4) running model simulations.
  dev_url: http://github.com/csdms/model_metadata

extra:
  recipe-maintainers:
    - mcflugen
