travis:
  secure:
    BINSTAR_TOKEN: nYiRUTcEfaMQMn4MsuljNjhXNtPnzcdxtThB1+9NJ39z8ZX2qc0FwttpqEbeJwWCKrkCVDZX62TiNZIMfsEwWy4KnjiHDy++wuzt/YGJh4pvhWhpun+78g1kEKdp86+1DAStm8RIrXCBQT2Z/Xn1vLRVOfNrO3Xliv7guFwmIA2duNbMZY7ZMT6A072Fr7kt8dnr7UzZbbhzUCpkZPODIMik9c5HEI0140d6F12YHJ0gpidFt9Y5HEmjZeQVJNKWKWszlkjc/imUCqDoyzdv7gVwjI6ayjXYswQYU+sCztQKSfZtfB7T7PAysw0Sy6a1oVCl0kMAZhAEPBwJ5AYSruu/Eg3eO9dcjmTtL1yTssDKPB2K2zVks7FZIDki3PmcgxdTLTQI47t30h/KOkHa9SFkseQ6HfYhq9OdN4OJsVYl2PQd17wBA3nMZXlOkGeBHeibiSLG0H8x8M/ABvliShgY797G1VUF3aF61dwDNS3kZxrlm3EtCzx6qZ9hQXlvLIs6cOz7bpqS/UJyLxhTYxBSBmSCCCjyC4A78C3AqMfwFK2091IDVBhHxtVod1q8WBmBEDr5n2fmQDPFOD2mIIpGgDQ2nafD9r1nnLifFqxDu12gmNHLDbjqob7huqk1Egx9lJ62O9eL8YXCERVvyxME+DnlMO5HdAMbJx3cw3c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
